version: '3'
services:

     db:
        image: postgres:12
        container_name: db
        volumes:
           - ./db_folder:/var/lib/postgresql/data 
        ports:
           - "5432:5432"
        environment:
           - ACCEPT_EULA=Y 
           - MSSQL_PID=postgres
           - POSTGRES_PASSWORD=Postgres2018!   

     api01:
        container_name: api01
        image: rinhabackend
        build:
          context: .
          dockerfile: RinhaBackend/Dockerfile
        depends_on:
          - db
          - redis
        ports:
          - "53340:80"
          - "53341:443"
        deploy:
          resources:
            limits:
              cpus: '0.3'
              memory: '0.4GB'
     api02:
        container_name: api02
        image: rinhabackend
        build:
          context: .
          dockerfile: RinhaBackend/Dockerfile
        depends_on:
          - db
          - redis
          - api01 #only to avoid conflit when creating database for the first time
        ports:
          - "53344:80"
          - "53345:443"
        deploy:
          resources:
            limits:
              cpus: '0.3'
              memory: '0.4GB'

     redis:
        image: redis
        container_name: cache
        ports:
          - "6379:6379"
        deploy:
          resources:
            limits:
              cpus: '0.3'
              memory: '0.3GB'
     proxy:
        container_name: proxy
        image: nginx:latest
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
          - api01
          - api02
        ports:
          - "9999:9999"
        deploy:
          resources:
            limits:
              cpus: '0.1'
              memory: '0.2GB'
         
     dbAdmin:
            image: dpage/pgadmin4:latest
            container_name: dbadmin
            ports:
               - "8080:80"
            environment:
               PGADMIN_DEFAULT_EMAIL: "teste@teste.com"
               PGADMIN_DEFAULT_PASSWORD: "PgAdmin2022!"
